accounts/urls.py
from django.urls import path
from .views import (
    register_page_view, 
    login_page_view, 
    logout_view,
    account_page_view,
    must_authenticate_view,
    unauthorized_view,
)

app_name = "accounts"
urlpatterns = [
    # Account management links
    path('register/', register_page_view, name="register"),
    path('login/', login_page_view, name="login"),
    path('my-account/', account_page_view, name="account"),
    path('logout/', logout_view, name="logout"),
    path('must-authenticate/',must_authenticate_view, name="must_authenticate"),
    path('unauthorized/',unauthorized_view, name="unauthorized"),
]

pages/urls.py
from django.urls import path
from .views import homepage_view, welcome_page_view


urlpatterns = [
    path('', homepage_view, name="home"),
    path('welcome/', welcome_page_view, name="welcome"),
]

password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
    path('vault/', include('vault.urls')),

    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset_templates/password_change_done.html'),
         name='password_change_done'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='password_reset_templates/password_change.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_templates/password_reset_confirm.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset_templates/password_reset_form.html'),
         name='password_reset'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_templates/password_reset_complete.html'),
         name='password_reset_complete'),
]

vault/urls.py
from django.urls import path
from .views import (
    update_entry_view,
    delete_entry_view,
    create_entry_view,
    )

app_name = "entry"
urlpatterns = [
    path('create/', create_entry_view, name='create'),
    path('<int:entry_id>/edit/', update_entry_view, name="edit"),
    path('<int:entry_id>/delete/', delete_entry_view, name='delete'),
]

pages/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% if show_add == True %}
	<div class="row d-flex justify-content-between">
		<div class="col-lg-6 col-md-12 justify-content-start">
			<section class=" text-start my-5 p-0">
				<div class="container">
				  <h1 class="h4">All Items</h1>
				</div>
			</section>
		</div>
		<div class="d-none d-lg-flex col-lg-6 justify-content-end align-items-center" >
			<form class="form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="search" name="q" id="id_q" placeholder="Search...">
				<button class="btn my-2 my-sm-0" id ="search-btn" style="outline:none;" type="submit">Search</button>
			</form>
		</div>
	</div>
{% endif %}

<div class="album ">
  <div class="row">
	  {% if not qs_list and query %}
		{% include 'snippets/no_items.html' %}
	  {% else %}
		  {% for field in qs_list %}
			<div class="col-sm-6 col-lg-4" id="{{ field.id }}">
			  <div class="card mb-4 p-4 shadow-sm">
				<div class="card-body p-2">
				  <h2 class="card-title">{{field.site_name | title}}</h2>
				  <p class="card-subtitle mb-5 text-muted"><a href="{{field.site_url}}">launch site</a></p>
				  <div class="d-flex justify-content-between align-items-center">
					<div class="btn-group">
					  <a class="responsive-button btn btn-outline-secondary" href="{% url 'entry:edit' entry_id=field.id %}">View</a>
					  <a class="responsive-button btn btn-outline-secondary show-alert" href="{% url 'entry:delete' entry_id=field.id %}">
						  Delete
					  </a>
					</div>
				  </div>
				</div>
			  </div>
			</div>

	       <!-- Delete popup -->
	  		<div class="modal hide" id="confirmModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
					<div class="modal-content">
					  <div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Delete Entry</h5>
					  </div>
					  <div class="modal-body">
						Are you sure you want to delete this entry?
					  </div>
					  <div class="modal-footer">
						<a type="button" class="btn btn-secondary" href="{% url 'home'%}">Cancel</a>
						<a type="submit" class="btn btn-primary text-center" href="{% url 'entry:delete' entry_id=field.id %}">Delete</a>
					  </div>
					</div>
				  </div>
			</div>
	  	  	<!-- End Delete popup -->
		  {% endfor %}
		  {% if show_add == True %}
			<div class="col-sm-6  col-lg-4">
				<div class="card mb-4" style="border: dashed 1.5px #252627">
					<div class="card-body d-flex justify-content-center align-items-center">
						<a class="btn btn-md add-entry-btn p-2" href="#createModal" data-toggle="modal">Add Entry</a>
					</div>
				</div>
			</div>
		  {% endif %}
	  {% endif %}

	  <div class="modal hide" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<h5 class="modal-title" id="exampleModalLabel2">Add Entry</h5>
		  </div>
		  <div class="modal-body">
			  {% include 'create_entry.html' %}
		  </div>
		</div>
	  </div>
  </div>
  </div>
</div>


<style type="text/css">
     .modal-body{
        font-size: 1rem;
     }

     .btn.btn-primary, .show-alert{
     	background-color: #D22D27;
     	color: white;
     	border: black;
     }

     .show-alert:hover{
        background-color: #F41D15;
     }

     .btn.btn-secondary{
     	background-color: #ffff;
     	color:#16151A;
     }

     .add-entry-btn{
     	border-color: #D22D27;
     	color: #D22D27;
     }

     .add-entry-btn:hover{
     	background-color: #D22D27;
     	color: white;
     }

     .responsive-button {
		  @media (min-width: 576px) { @extend .btn-sm }
		  @media (min-width: 768px) { @extend .btn-md }
}
</style>

<script type="text/javascript">
	document.getElementById("id_q").value = "{{query}}"
</script>

{% endblock content %}

pages/templates/welcome_page.html
{% extends 'base.html' %}

{% block title %}
<title>Easy Pass|Welcome</title>
{% endblock title %}

{% block content %}

<div class="container align-items-center">
  <div class="row mt-5 pt-5">
    <div class="col-lg-12 text-center p-4">
      <h1>Welcome to Easy Pass</h1>
      <p class="lead text-muted mb-5">Manage your passwords in an easier way.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 d-flex p-4 justify-content-center align-items-center">
      <a class="btn btn-lg btn-dark  p-3 " style="width:10rem; border-radius: 7px 0px 0px 7px;"
       href="{% url 'accounts:login'%}">Log in
      </a>
      <a class="btn btn-lg p-3 " style="background-color: #D22D27;
        color: #FFFF; width:10rem; border-radius: 0px 7px 7px 0px;" href="{% url 'accounts:register'%}">Register
      </a>
    </div>
  </div>
</div>
{% endblock content %}