accounts/urls.py
from django.urls import path
from .views import (
    register_page_view, 
    login_page_view, 
    logout_view,
    account_page_view,
    must_authenticate_view,
    unauthorized_view,
)

app_name = "accounts"
urlpatterns = [
    # Account management links
    path('register/', register_page_view, name="register"),
    path('login/', login_page_view, name="login"),
    path('my-account/', account_page_view, name="account"),
    path('logout/', logout_view, name="logout"),
    path('must-authenticate/',must_authenticate_view, name="must_authenticate"),
    path('unauthorized/',unauthorized_view, name="unauthorized"),
]

pages/urls.py
from django.urls import path
from .views import homepage_view, welcome_page_view


urlpatterns = [
    path('', homepage_view, name="home"),
    path('welcome/', welcome_page_view, name="welcome"),
]

password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
    path('vault/', include('vault.urls')),

    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset_templates/password_change_done.html'),
         name='password_change_done'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='password_reset_templates/password_change.html'),
         name='password_change'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_templates/password_reset_confirm.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset_templates/password_reset_form.html'),
         name='password_reset'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_templates/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/snippets/base_css.html
<style type="text/css">
    body{
        background-color: #FFF8EB;
        font-size: 10px;
        min-height:100vh;
    }

    main{
        min-height:75vh;
    }

    p{
       font-size: 0.9rem;
    }

    a{
        color: #D22D27;
    }

    .btn.btn-secondary{
      background-color: #D22D27;
      color: #FFFF;
      border:none;
    }

    .navbar-brand{
        color: #16151A;
        font-size:1.45rem;
        font-weight: bold;
    }

    .nav-link{
        color: #16151A;
        font-size:1.15rem;
    }

    button.navbar-toggler{
        background-color: #FFFF;
    }

    nav{
        background-color: #FFFF;
        border: bottom 20px #0A2240;
    }

    #search-btn, btn{
      background-color: #D22D27;
      color: #FFFF;
      rounded: 10px;
    }

    .card{
        height: 14rem;
    }
	
    .card-title{
	font-size:1.5rem;
	overflow-wrap: break-word;
    }

    .card-body{
        font-size:1.5rem;
    }

    .card-body p{
		 font-size:0.9rem;
    }
	
</style>

templates/snippets/footer.html
<style type="text/css">
  @import url('https://fonts.googleapis.com/css2?family=Titillium+Web:wght@700&display=swap');
  .footer-main {
      padding: 2% 7% 1% 7%;
      color: #646771;
      background-color: #16151a;
      border-radius: 0px 0px 0px 0px;

  }
  ul {
      list-style-type: none;
      margin: 0;
      padding: 0
  }
  ul>li {
      padding: 0.4rem
  }

  .social{
    bottom: 0px;
    right: 0px;
  }
  .social>a>i {
      color: white;

    }
  .social>a>i:hover {
      color: #957bda;
      cursor: pointer
  }
  .heading {
      font-family: 'Titillium Web', sans-serif;
      color: white;
  }
  .divider {
      border-top: 0.2px solid rgba(189, 196, 203, 0.5);
  }
</style>

<footer>
  <div class="mt-5">
      <div class="footer-main" >
          <div class="row p-2">
                  <div class="col-9 footer-text">
                      <div class="d-flex justify-content-start align-items-center">
                          <h1 class="font-weight-bold mr-2 px-3" style="color:#16151a; background-color:#D22D27">E</h1>
                          <h1 style="color: #D22D27" > Pass </h1>
                      </div>
                      <p class="card-text mt-3" style="font-size:1.3rem;">Manage your passwords more easily.<br> Store all of your passwords in one secure place.</p>
                  </div>
                  <div class="col-3 footer-text align-text-bottom position-relative">
                      <div class="social d-flex align-items-center position-absolute ">
                        <a class="btn social-icon button" href="https://linkedin.com/in/notarkhit">
                          <i class="fa fa-linkedin-square fa-lg"></i>
                        </a>
                        <a class="btn social-icon button" href="https://github.com/notarkhit">
                          <i class="fa fa-github-alt fa-lg"></i>
                        </a>
                      </div>
                  </div>
              </div>
          <div class="divider my-2"></div>
      </div>
  </div>
</footer>

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg border-bottom border-danger navbar-light mb-5">
  {% if not request.user.is_authenticated %}
  <a class="navbar-brand" href="{%url 'home'%}" style="font-size: 1.6rem">Easy Pass</a>
  {% else %}
  <a class="navbar-brand" href="{%url 'home'%}">Hello, {{request.user.username}}</a>
  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if request.user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item active" >
          <a class="nav-link" href="{% url 'accounts:account' %}">My Account</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0 d-lg-none">
        <input class="form-control mr-sm-2" type="search" name="q" id="id_q" placeholder="Search...">
        <button class="btn my-2 my-sm-0" id ="search-btn" type="submit">Search</button>
      </form>
    {% endif%}
  </div>
</nav>